runtime: python39
instance_class: F2

entrypoint: gunicorn -w 1 -k uvicorn.workers.UvicornWorker main:app --timeout 300

env_variables:
  API_KEY: "AIzaSyCNjAzI3AYUDHlcPuXbZ42fQFhzxmZ4qrw"
  PROJECT_ID: "vc-interview-agent"
  LOCATION: "us-central1"
  ENVIRONMENT: "production"

liveness_check:
  path: "/health"
  check_interval_sec: 30
  timeout_sec: 4
  failure_threshold: 2
  success_threshold: 2

readiness_check:
  path: "/health"
  check_interval_sec: 30
  timeout_sec: 4
  failure_threshold: 2
  success_threshold: 2
