runtime: python39
instance_class: F2

entrypoint: gunicorn -w 1 -k uvicorn.workers.UvicornWorker main:app

env_variables:
  API_KEY: "AIzaSyCNjAzI3AYUDHlcPuXbZ42fQFhzxmZ4qrw"
  PROJECT_ID: "vc-interview-agent"
  LOCATION: "us-central1"
  ENVIRONMENT: "production"
