name: Deploy to Google Cloud Run

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Google Auth
        id: auth
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}
          project_id: ${{ secrets.GCP_PROJECT_ID }}

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v1

      - name: Authorize Docker push
        run: gcloud auth configure-docker

      - name: Build and push container
        run: |
          docker build -t gcr.io/${{ secrets.GCP_PROJECT_ID }}/ventureai:${{ github.sha }} .
          docker push gcr.io/${{ secrets.GCP_PROJECT_ID }}/ventureai:${{ github.sha }}

      - name: Deploy to Cloud Run
        id: deploy
        uses: google-github-actions/deploy-cloudrun@v1
        with:
          service: ventureai
          image: gcr.io/${{ secrets.GCP_PROJECT_ID }}/ventureai:${{ github.sha }}
          region: us-central1
          flags: --timeout=600s --memory=512Mi --cpu=1 --min-instances=1 --max-instances=10 --verbosity=debug --log-http
          env_vars: |
            ENVIRONMENT=production

      - name: Show Output
        run: |
          echo "Deployed URL: ${{ steps.deploy.outputs.url }}"
          echo "View logs at: https://console.cloud.google.com/run/detail/us-central1/ventureai/logs"
